golang-openapi-generator-check:
    stage: check-tool
    extends:
        - .check-docker
    variables:
      CONTEXT_PATH: tools/golang-openapi-generator
      DOCKERFILE_PATH: Dockerfile
    rules:
      - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
        changes:
          - tools/golang-openapi-generator/**/*

golang-openapi-generator-build:
    stage: build-tool
    extends:
        - .build-docker
    variables:
      CONTEXT_PATH: tools/golang-openapi-generator
      IMAGE_NAME: tools/golang-openapi-generator
      DOCKERFILE_PATH: Dockerfile
    rules:
      - if: $CI_COMMIT_TAG =~ /^golang-openapi-generator-(\d+(\.\d+(\.\d+)?)?)$/
        variables:
          LATEST: 1
      - if: $CI_COMMIT_TAG =~ /^golang-openapi-generator-(\d+(\.\d+(\.\d+)?)?(-[a-z0-9-]+)?)$/
