version: '3.7'
services:
  db:
    image: postgres
    container_name: example_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: example_database
    ports:
      - "5432:5432"
