git-check:
    stage: check-tool
    extends:
        - .check-docker
    variables:
      CONTEXT_PATH: tools/git
      DOCKERFILE_PATH: Dockerfile
    rules:
      - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
        changes:
          - base/alpine/**/*
          - tools/git/**/*

git-build:
    stage: build-tool
    extends:
        - .build-docker
    variables:
      CONTEXT_PATH: tools/git
      IMAGE_NAME: tools/git
      DOCKERFILE_PATH: Dockerfile
    rules:
      - if: $CI_COMMIT_TAG =~ /^git-(\d+(\.\d+(\.\d+)?)?)$/
        variables:
          LATEST: 1
      - if: $CI_COMMIT_TAG =~ /^git-(\d+(\.\d+(\.\d+)?)?(-[a-z0-9-]+)?)$/
