golangci-lint-check:
    stage: check
    extends:
        - .check-docker
    variables:
      CONTEXT_PATH: base/golangci-lint
      DOCKERFILE_PATH: Dockerfile
    rules:
      - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
        changes:
          - base/golangci-lint/**/*

golangci-lint-build:
    stage: build-base
    extends:
        - .build-docker
    variables:
      CONTEXT_PATH: base/golangci-lint
      IMAGE_NAME: base/golangci-lint
      DOCKERFILE_PATH: Dockerfile
    rules:
      - if: $CI_COMMIT_TAG =~ /^golangci-lint-(\d+(\.\d+(\.\d+)?)?(-[a-z0-9-]+)?)$/
        variables:
          LATEST: 1
        changes:
          - base/golangci-lint/**/*
