docker-builder-check:
    stage: check
    extends:
        - .check-docker
    variables:
      CONTEXT_PATH: tools/docker-builder
      DOCKERFILE_PATH: Dockerfile
    rules:
      - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
        changes:
          - tools/docker-builder/**/*

docker-builder-build:
    stage: build-tool
    extends:
        - .build-docker
    variables:
      CONTEXT_PATH: tools/docker-builder
      IMAGE_NAME: tools/docker-builder
      DOCKERFILE_PATH: Dockerfile
    rules:
      - if: $CI_COMMIT_TAG =~ /^docker-builder-(\d+(\.\d+(\.\d+)?)?)$/
        variables:
          LATEST: 1
      - if: $CI_COMMIT_TAG =~ /^docker-builder-(\d+(\.\d+(\.\d+)?)?(-[a-z0-9-]+)?)$/
