golang-check:
    stage: check
    extends:
        - .check-docker
    variables:
      CONTEXT_PATH: base/golang
      DOCKERFILE_PATH: Dockerfile
    rules:
      - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
        changes:
          - base/golang/**/*

golang-build:
    stage: build-base
    extends:
        - .build-docker
    variables:
      CONTEXT_PATH: base/golang
      IMAGE_NAME: base/golang
      DOCKERFILE_PATH: Dockerfile
    rules:
      - if: $CI_COMMIT_TAG =~ /^golang-(\d+(\.\d+(\.\d+)?)?(-[a-z0-9-]+)?)$/
        variables:
          LATEST: 1
        changes:
          - base/golang/**/*
