stages:
  - check
  - build-base

  - check-tool
  - check-app
  - check-app-build
  - check-app-dev

  - build-tool
  - build-app
  - build-app-build
  - build-app-dev

include:
  - /base/.gitlab-ci.yml
  - /tools/.gitlab-ci.yml

.check-docker:
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  variables: # Example set of required variables
    CONTEXT_PATH: example/image
    DOCKERFILE_PATH: Dockerfile
  before_script:
    - echo ${DOCKER_AUTH_CONFIG} > /kaniko/.docker/config.json
  script:
    - /kaniko/executor
      --context ${CI_PROJECT_DIR}/${CONTEXT_PATH}
      --dockerfile ${DOCKERFILE_PATH}
      --no-push
  tags:
    - k8s

.build-docker:
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  variables: # Example set of required variables
    CONTEXT_PATH: example/image
    DOCKERFILE_PATH: Dockerfile
    IMAGE_NAME: example/foo
  before_script:
    - echo ${DOCKER_AUTH_CONFIG} > /kaniko/.docker/config.json
  script:
    - echo "Image name - ${IMAGE_NAME}"
    - |-
      if [[ ! -z $CI_COMMIT_TAG ]]; then
          IMAGE_VERSION=$(echo $CI_COMMIT_TAG | sed -E 's/[^0-9]+//')
          echo "Pushing version - ${IMAGE_VERSION}"
          DESTINATION=" --destination ${REGISTRY_URL}/${IMAGE_NAME}:${IMAGE_VERSION}"
      fi
    - |-
      if [[ ! -z $LATEST ]]; then
          echo "Pushing latest tag"
          DESTINATION="${DESTINATION} --destination ${REGISTRY_URL}/${IMAGE_NAME}:latest"
      fi
    - /kaniko/executor
      --context ${CI_PROJECT_DIR}/${CONTEXT_PATH}
      --dockerfile ${DOCKERFILE_PATH}
      ${DESTINATION}
  tags:
    - k8s
