kube-deployer-check:
    stage: check
    extends:
        - .check-docker
    variables:
      CONTEXT_PATH: tools/kube-deployer
      DOCKERFILE_PATH: Dockerfile
    rules:
      - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
        changes:
          - base/alpine/**/*
          - tools/kube-deployer/**/*

kube-deployer-build:
    stage: build-tool
    extends:
        - .build-docker
    variables:
      CONTEXT_PATH: tools/kube-deployer
      IMAGE_NAME: tools/kube-deployer
      DOCKERFILE_PATH: Dockerfile
    rules:
      - if: $CI_COMMIT_TAG =~ /^kube-deployer-(\d+(\.\d+(\.\d+)?)?)$/
        variables:
          LATEST: 1
      - if: $CI_COMMIT_TAG =~ /^kube-deployer-(\d+(\.\d+(\.\d+)?)?(-[a-z0-9-]+)?)$/
