redoc-ui-check:
  stage: check-tool
  extends:
    - .check-docker
  variables:
    CONTEXT_PATH: tools/redoc-ui
    DOCKERFILE_PATH: Dockerfile
  rules:
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
      changes:
        - tools/redoc-ui/**/*

redoc-ui-build:
  stage: build-tool
  extends:
    - .build-docker
  variables:
    CONTEXT_PATH: tools/redoc-ui
    IMAGE_NAME: tools/redoc-ui
    DOCKERFILE_PATH: Dockerfile
  rules:
    - if: $CI_COMMIT_TAG =~ /^redoc-ui-(\d+(\.\d+(\.\d+)?)?)$/
      variables:
        LATEST: 1
    - if: $CI_COMMIT_TAG =~ /^redoc-ui-(\d+(\.\d+(\.\d+)?)?(-[a-z0-9-]+)?)$/
