argocd-check:
    stage: check
    extends:
        - .check-docker
    variables:
      CONTEXT_PATH: tools/argocd
      DOCKERFILE_PATH: Dockerfile
    rules:
      - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
        changes:
          - base/alpine/**/*
          - tools/argocd/**/*

argocd-build:
    stage: build-tool
    extends:
        - .build-docker
    variables:
      CONTEXT_PATH: tools/argocd
      IMAGE_NAME: tools/argocd
      DOCKERFILE_PATH: Dockerfile
    rules:
      - if: $CI_COMMIT_TAG =~ /^argocd-(\d+(\.\d+(\.\d+)?)?)$/
        variables:
          LATEST: 1
      - if: $CI_COMMIT_TAG =~ /^argocd-(\d+(\.\d+(\.\d+)?)?(-[a-z0-9-]+)?)$/
