golang-alpine-check:
    stage: check
    extends:
        - .check-docker
    variables:
      CONTEXT_PATH: base/golang-alpine
      DOCKERFILE_PATH: Dockerfile
    rules:
      - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
        changes:
          - base/golang-alpine/**/*

golang-alpine-build:
    stage: build-base
    extends:
        - .build-docker
    variables:
      CONTEXT_PATH: base/golang-alpine
      IMAGE_NAME: base/golang-alpine
      DOCKERFILE_PATH: Dockerfile
    rules:
      - if: $CI_COMMIT_TAG =~ /^golang-alpine-(\d+(\.\d+(\.\d+)?)?(-[a-z0-9-]+)?)$/
        variables:
          LATEST: 1
        changes:
          - base/golang-alpine/**/*
