dynamodb-check:
    stage: check
    extends:
        - .check-docker
    variables:
      CONTEXT_PATH: base/dynamodb
      DOCKERFILE_PATH: Dockerfile
    rules:
      - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
        changes:
          - base/dynamodb/**/*

dynamodb-build:
    stage: build-base
    extends:
        - .build-docker
    variables:
      CONTEXT_PATH: base/dynamodb
      IMAGE_NAME: base/dynamodb
      DOCKERFILE_PATH: Dockerfile
      LATEST: 1
    rules:
      - if: $CI_COMMIT_BRANCH == "main"
        changes:
          - base/dynamodb/**/*
