npm-package-builder-check:
    stage: check-tool
    extends:
        - .check-docker
    variables:
      CONTEXT_PATH: tools/npm-package-builder
      DOCKERFILE_PATH: Dockerfile
    rules:
      - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
        changes:
          - base/node/**/*
          - tools/npm-package-builder/**/*

npm-package-builder-build:
    stage: build-tool
    extends:
        - .build-docker
    variables:
      CONTEXT_PATH: tools/npm-package-builder
      IMAGE_NAME: tools/npm-package-builder
      DOCKERFILE_PATH: Dockerfile
    rules:
      - if: $CI_COMMIT_TAG =~ /^npm-package-builder-(\d+(\.\d+(\.\d+)?)?)$/
        variables:
          LATEST: 1
      - if: $CI_COMMIT_TAG =~ /^npm-package-builder-(\d+(\.\d+(\.\d+)?)?(-[a-z0-9-]+)?)$/
