python-proto-builder-check:
    stage: check-tool
    extends:
        - .check-docker
    variables:
      CONTEXT_PATH: tools/python-proto-builder
      DOCKERFILE_PATH: Dockerfile
    rules:
      - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
        changes:
          - base/python/**/*
          - tools/python-proto-builder/**/*

python-proto-builder-build:
    stage: build-tool
    extends:
        - .build-docker
    variables:
      CONTEXT_PATH: tools/python-proto-builder
      IMAGE_NAME: tools/python-proto-builder
      DOCKERFILE_PATH: Dockerfile
    rules:
      - if: $CI_COMMIT_TAG =~ /^python-proto-builder-(\d+(\.\d+(\.\d+)?)?)$/
        variables:
          LATEST: 1
      - if: $CI_COMMIT_TAG =~ /^python-proto-builder-(\d+(\.\d+(\.\d+)?)?(-[a-z0-9-]+)?)$/
