golang-proto-builder-check:
    stage: check-tool
    extends:
        - .check-docker
    variables:
      CONTEXT_PATH: tools/golang-proto-builder
      DOCKERFILE_PATH: Dockerfile
    rules:
      - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
        changes:
          - base/golang-alpine/**/*
          - tools/golang-proto-builder/**/*

golang-proto-builder-build:
    stage: build-tool
    extends:
        - .build-docker
    variables:
      CONTEXT_PATH: tools/golang-proto-builder
      IMAGE_NAME: tools/golang-proto-builder
      DOCKERFILE_PATH: Dockerfile
    rules:
      - if: $CI_COMMIT_TAG =~ /^golang-proto-builder-(\d+(\.\d+(\.\d+)?)?)$/
        variables:
          LATEST: 1
      - if: $CI_COMMIT_TAG =~ /^golang-proto-builder-(\d+(\.\d+(\.\d+)?)?(-[a-z0-9-]+)?)$/
