python-ci-check:
    stage: check
    extends:
        - .check-docker
    variables:
      CONTEXT_PATH: base/python-ci
      DOCKERFILE_PATH: Dockerfile
    rules:
      - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
        changes:
          - base/python-ci/**/*

python-ci-build:
    stage: build-base
    extends:
        - .build-docker
    variables:
      CONTEXT_PATH: base/python-ci
      IMAGE_NAME: base/python-ci
      DOCKERFILE_PATH: Dockerfile
      LATEST: 1
    rules:
      - if: $CI_COMMIT_BRANCH == "main"
        changes:
          - base/python-ci/**/*
